# Introducción a la Ciencia de Datos — Clase 01

## Del dato a la pregunta: un pequeño proyecto con Python

**Ruta de hoy**

`Pregunta → Datos → Python → Exploración → Análisis → Visualización → Conclusión`

En esta primera clase no buscamos aprender toda la sintaxis de Python. Buscamos recorrer, por primera vez, el ciclo completo de un pequeño proyecto de Ciencia de Datos.

> **Idea central:** Python es una herramienta; la Ciencia de Datos empieza con una pregunta.

## 0. Preparación

Este notebook utiliza tres herramientas principales:

- **NumPy**: cálculo numérico y arreglos.
- **Pandas**: datos tabulares.
- **Matplotlib**: visualización.

Los archivos CSV de esta carpeta contienen **datos sintéticos preparados con fines educativos**. No deben interpretarse como mediciones oficiales de calidad del aire ni como estadísticas oficiales de las ciudades.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("¡Listos para hacer Ciencia de Datos!")

¡Listos para hacer Ciencia de Datos!

# 1. Python como herramienta

Antes de trabajar con tablas, recordemos algunas piezas mínimas de Python.

In [2]:
nombre = "Ciencia de Datos"
semestre = 1
temperatura = 28.5

print(nombre)
print(semestre)
print(temperatura)

Ciencia de Datos
1
28.5

In [3]:
temperaturas = [27, 29, 28, 30, 31, 29]

print("Número de observaciones:", len(temperaturas))
print("Mínimo:", min(temperaturas))
print("Máximo:", max(temperaturas))
print("Promedio:", sum(temperaturas) / len(temperaturas))

Número de observaciones: 6
Mínimo: 27
Máximo: 31
Promedio: 29.0

### Pregunta rápida

¿Qué ocurre cuando una lista de Python empieza a contener miles o millones de valores y necesitamos hacer cálculos repetidamente?

Aquí aparece **NumPy**.

# 2. NumPy: pensar en arreglos

In [4]:
temperaturas_np = np.array(temperaturas)

temperaturas_np

array([27, 29, 28, 30, 31, 29])

In [5]:
print("Promedio:", temperaturas_np.mean())
print("Desviación estándar:", temperaturas_np.std())
print("Mínimo:", temperaturas_np.min())
print("Máximo:", temperaturas_np.max())

Promedio: 29.0
Desviación estándar: 1.2909944487358056
Mínimo: 27
Máximo: 31

In [6]:
temperaturas_np - temperaturas_np.mean()

array([-2.,  0., -1.,  1.,  2.,  0.])

La última operación es importante: NumPy permite aplicar una operación a todo el arreglo de manera compacta y eficiente.

No necesitamos recorrer manualmente cada elemento para restarle el promedio.

# 3. Nuestro primer conjunto de datos

In [7]:
df = pd.read_csv("colombia_cities_air_quality_demo.csv")
df

             city  pm25  temperature_c  population  green_area_pct
0          Bogotá  18.4           14.2     7800000             4.8
1        Medellín  15.2           22.1     2500000             5.7
2            Cali  16.3           24.7     2300000             6.1
3    Barranquilla  12.7           29.1     1300000             7.4
4       Cartagena  11.8           28.5     1100000             7.9
5     Bucaramanga  14.9           23.4      600000             6.4
6         Pereira  13.6           21.2      480000             6.8
7       Manizales  12.9           17.5      450000             7.2
8     Santa Marta  10.9           28.7      550000             8.1
9          Ibagué  14.1           22.8      550000             6.6
10  Villavicencio  12.3           26.1      560000             7.5
11          Pasto   9.8           13.5      390000             8.0

In [8]:
df.head()

           city  pm25  temperature_c  population  green_area_pct
0        Bogotá  18.4           14.2     7800000             4.8
1      Medellín  15.2           22.1     2500000             5.7
2          Cali  16.3           24.7     2300000             6.1
3  Barranquilla  12.7           29.1     1300000             7.4
4     Cartagena  11.8           28.5     1100000             7.9

In [9]:
df.shape

(12, 5)

In [10]:
df.columns

Index(['city', 'pm25', 'temperature_c', 'population', 'green_area_pct'], dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   city            12 non-null     object
 1   pm25            12 non-null     float64
 2   temperature_c   12 non-null     float64
 3   population      12 non-null     int64
 4   green_area_pct  12 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 612.0+ bytes

In [12]:
df.describe()

            pm25  temperature_c    population  green_area_pct
count  12.000000      12.000000  1.200000e+01       12.000000
mean   13.575000      22.650000  1.548333e+06        6.875000
std     2.389037       5.335729  2.097088e+06        1.008261
min     9.800000      13.500000  3.900000e+05        4.800000
25%    12.175000      20.275000  5.325000e+05        6.325000
50%    13.250000      23.100000  5.800000e+05        7.000000
75%    14.975000      26.700000  1.550000e+06        7.600000
max    18.400000      29.100000  7.800000e+06        8.100000

## Interpretación

Una tabla de datos puede pensarse como una matriz:

- cada **fila** representa una observación;
- cada **columna** representa una variable;
- cada celda contiene un valor observado.

Pero una tabla por sí sola todavía no es conocimiento. Necesitamos formular preguntas.

# 4. Pregunta de investigación de hoy

> **¿Qué podemos aprender sobre el PM2.5 de estas ciudades a partir de los datos?**

No intentaremos resolver un problema científico real. El objetivo es aprender el flujo de trabajo.

# 5. Seleccionar variables

In [13]:
df["city"]

0            Bogotá
1          Medellín
2              Cali
3      Barranquilla
4         Cartagena
5       Bucaramanga
6           Pereira
7         Manizales
8       Santa Marta
9            Ibagué
10    Villavicencio
11            Pasto
Name: city, dtype: object

In [14]:
df["pm25"]

0     18.4
1     15.2
2     16.3
3     12.7
4     11.8
5     14.9
6     13.6
7     12.9
8     10.9
9     14.1
10    12.3
11     9.8
Name: pm25, dtype: float64

In [15]:
df[["city", "pm25"]]

             city  pm25
0          Bogotá  18.4
1        Medellín  15.2
2            Cali  16.3
3    Barranquilla  12.7
4       Cartagena  11.8
5     Bucaramanga  14.9
6         Pereira  13.6
7       Manizales  12.9
8     Santa Marta  10.9
9          Ibagué  14.1
10  Villavicencio  12.3
11          Pasto   9.8

In [16]:
df[["city", "pm25", "temperature_c"]]

             city  pm25  temperature_c
0          Bogotá  18.4           14.2
1        Medellín  15.2           22.1
2            Cali  16.3           24.7
3    Barranquilla  12.7           29.1
4       Cartagena  11.8           28.5
5     Bucaramanga  14.9           23.4
6         Pereira  13.6           21.2
7       Manizales  12.9           17.5
8     Santa Marta  10.9           28.7
9          Ibagué  14.1           22.8
10  Villavicencio  12.3           26.1
11          Pasto   9.8           13.5

### Mini-ejercicio 1

Obtén únicamente las columnas `city`, `temperature_c` y `green_area_pct`.

Después pregunta:

**¿Qué ciudad tiene el mayor porcentaje de área verde en este conjunto?**

In [ ]:
# Escribe aquí tu solución

# 6. Estadística descriptiva

In [ ]:
mean_pm25 = df["pm25"].mean()
median_pm25 = df["pm25"].median()
std_pm25 = df["pm25"].std()

print("Promedio:", mean_pm25)
print("Mediana:", median_pm25)
print("Desviación estándar:", std_pm25)

### ¿Por qué mirar más de una medida?

El promedio resume, pero no cuenta toda la historia.

Podemos comparar:

- promedio;
- mediana;
- mínimo y máximo;
- dispersión.

Más adelante estudiaremos estas ideas formalmente.

# 7. Filtrar datos

In [ ]:
df[df["pm25"] > 15]

In [ ]:
df[df["temperature_c"] > 25]

### Mini-ejercicio 2

Encuentra las ciudades cuyo PM2.5 sea menor que el promedio.

Pista: puedes reutilizar `mean_pm25`.

In [ ]:
# Escribe aquí tu solución

# 8. Ordenar datos

In [ ]:
df.sort_values("pm25", ascending=False)

### Pregunta

¿Cuáles son las tres ciudades con mayor PM2.5?

In [ ]:
df.sort_values("pm25", ascending=False).head(3)

# 9. Visualización: convertir datos en una imagen

In [ ]:
plt.figure(figsize=(10, 5))

plt.bar(df["city"], df["pm25"])

plt.xlabel("Ciudad")
plt.ylabel("PM2.5")
plt.title("PM2.5 en ciudades colombianas — datos demostrativos")

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

### Pregunta para discutir

**¿Qué nos permite ver la gráfica que era más difícil de ver en la tabla?**

La visualización no sustituye al análisis. Nos ayuda a encontrar patrones, diferencias y posibles preguntas.

# 10. Buscar relaciones

In [ ]:
plt.figure(figsize=(7, 5))

plt.scatter(df["temperature_c"], df["pm25"])

plt.xlabel("Temperatura (°C)")
plt.ylabel("PM2.5")
plt.title("Temperatura vs. PM2.5 — datos demostrativos")

plt.tight_layout()
plt.show()

### Importante

Una gráfica puede sugerir una relación, pero **ver una tendencia no demuestra causalidad**.

En próximas clases aprenderemos herramientas para estudiar relaciones de manera más rigurosa.

# 11. Una pequeña transformación con NumPy

In [ ]:
df["pm25_centered"] = df["pm25"] - df["pm25"].mean()

df[["city", "pm25", "pm25_centered"]]

Hemos creado una nueva variable a partir de una variable existente.

Esto es una primera aproximación a la idea de **transformación y construcción de variables**.

# 12. Mini-proyecto

Ahora trabaja como científico/a de datos.

Usa el conjunto de datos para responder:

1. ¿Cuál es la ciudad con mayor PM2.5?
2. ¿Cuál es la ciudad con menor PM2.5?
3. ¿Cuál es el PM2.5 promedio?
4. ¿Qué ciudades están por encima del promedio?
5. ¿Parece existir alguna relación entre temperatura y PM2.5?
6. Produce una gráfica que ayude a comunicar uno de tus hallazgos.
7. Escribe una conclusión de 2–3 frases.

### Regla

Una buena respuesta no es solamente un número.

Debe contener:

**resultado + evidencia + interpretación**

In [ ]:
# Tu análisis comienza aquí.

# 1. Mayor PM2.5


# 2. Menor PM2.5


# 3. Promedio


# 4. Ciudades por encima del promedio


# 5. Relación temperatura-PM2.5


# 6. Tu gráfica


# 7. Tu conclusión

# 13. Segundo dataset: una nueva pregunta

Ahora podemos cambiar de problema sin cambiar completamente de herramientas.

Carga el segundo dataset:

`colombia_cities_social_demo.csv`

Contiene variables sociales sintéticas preparadas para practicar análisis exploratorio.

In [ ]:
social = pd.read_csv("colombia_cities_social_demo.csv")
social.head()

In [ ]:
social.describe()

### Reto

Explora la relación entre:

- porcentaje de finalización escolar;
- desempleo;
- acceso a espacios verdes.

Elige una pregunta propia y produce una tabla o una gráfica que ayude a responderla.

In [ ]:
# Escribe aquí tu pregunta y tu análisis.

# 14. El ecosistema

Hoy hemos abierto tres puertas:

`NumPy → cálculo numérico`

`Pandas → datos tabulares`

`Matplotlib → visualización`

Más adelante encontraremos otras herramientas:

`SciPy → computación científica`

`scikit-learn → aprendizaje automático`

`statsmodels → estadística y modelos`

`Seaborn → visualización estadística`

Pero no necesitamos aprenderlas todas hoy.

## El objetivo no es memorizar librerías.

El objetivo es aprender a recorrer este ciclo:

**Pregunta → Datos → Exploración → Análisis → Visualización → Evidencia → Conclusión**

Y, sobre todo:

> **No queremos aprender comandos. Queremos aprender a formular preguntas y utilizar herramientas computacionales para responderlas con datos.**

# 15. Cierre: cinco preguntas

Antes de terminar, intenta responder sin mirar el código:

1. ¿Qué representa una fila de un DataFrame?
2. ¿Qué representa una columna?
3. ¿Para qué usamos NumPy?
4. ¿Para qué usamos Pandas?
5. ¿Para qué usamos Matplotlib?

Y una última pregunta:

> **¿Qué pregunta sobre tu ciudad, tu universidad o tu comunidad te gustaría responder usando datos?**